
services:
  localaws:
    image: localstack/localstack-full
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "8083:8083"
    environment:
      - SERVICES=dynamodb,cloudwatch,firehose,kinesis,lambda,redshift,s3,sns,ses,sqs,stepfunctions
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker_reuse
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=sa-east-1
      - PORT_WEB_UI=8083
      - LAMBDA_DOCKER_NETWORK=localstack-tutorial
      - KINESIS_PROVIDER=kinesalite
    volumes:
      - "/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"